version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trader_db
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trader_network

  api:
    build:
      context: ./trader_api
      dockerfile: Dockerfile  # Define explicit Dockerfile, se necessário
      args:
        USER_ID: 1001
        GROUP_ID: 1001
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./trader_api:/usr/local/trader/api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=trader_db
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=admin
    networks:
      - trader_network
    env_file:
      - ./trader_api/.env

volumes:
  postgres_data:

networks:
  trader_network:
