version: '3.8'

services:
  # Agente do Portainer
  agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - trader_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  # Serviço do Traefik (Proxy reverso)
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      #defina a mesma rede que você criou para o traefik
      - --providers.docker.network=trader_network
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      # Config para SSL Lets Encrypt
      # altere para seu e-mail
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=suporte@ferreiratrader.com.br
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Global HTTP -> HTTPS
      #- --entrypoints.web.http.redirections.entryPoint.to=websecure
      #- --entrypoints.web.http.redirections.entryPoint.scheme=https
      #- --api
      - --log.level=DEBUG
    container_name: traefik
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Para acessar os containers Docker
      - ./traefik_data:/etc/traefik  # Persistência de configuração
      - ./acme.json:/acme.json       # Certificados SSL gerados automaticamente
      - traefik_certificates:/letsencrypt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - trader_network  

  # Serviço de banco de dados
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trader_db
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trader_network

  # Serviço da API (Django)
  api:
    build:
      context: ./trader_api
      dockerfile: Dockerfile  # Define o Dockerfile explicitamente, se necessário
      args:
        USER_ID: 1001
        GROUP_ID: 1001
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./trader_api:/usr/local/trader/api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=trader_db
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=admin
    networks:
      - trader_network
    env_file:
      - ./trader_api/.env
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`alfa-app.ferreiratrader.com.br`)"  # Substitua pelo domínio da API
        - "traefik.http.services.api.loadbalancer.server.port=8000"  # Porta onde a aplicação escuta
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=myresolver"
        # Serviço do Portainer
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    networks:
      - trader_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`server.ferreiratrader.com.br`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
volumes:
  postgres_data:
  
  traefik_certificates:
    driver: local
networks:
  trader_network:
    driver: bridge
