server {
    listen 80;
    server_name localhost;

    # Redireciona as requisições para o Gunicorn (que está rodando no contêiner "web")
    location / {
        proxy_pass http://api:8000;  # Nome do serviço do Gunicorn (no docker-compose.yml)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Diretório de arquivos estáticos
    location /static/ {
        alias /app/static/;
    }

    # Diretório de arquivos de mídia
    location /media/ {
        alias /app/media/;
    }
}