# Generated by Django 3.2.16 on 2024-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('team', 'Team')], default='student', max_length=10),
        ),
    ]
