# Generated by Django 3.2.16 on 2024-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_pass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_pass',
            name='consum',
            field=models.BooleanField(default=False),
        ),
    ]
