# Use uma imagem base com Python
FROM python:3.10

# Defina os argumentos passados pelo docker-compose
ARG USER_ID
ARG GROUP_ID

# Crie o grupo e usuário com UID e GID
RUN groupadd -g ${GROUP_ID} mygroup && \
    useradd -u ${USER_ID} -g ${GROUP_ID} -m myuser

# Altere o usuário do container para o usuário criado
USER myuser

# Define o diretório de trabalho dentro do contêiner
WORKDIR /usr/local/trader/api

# Copia o arquivo requirements.txt para o contêiner
COPY requirements.txt /usr/local/trader/api/

# Instala as dependências
RUN pip install -U pip
RUN pip install -r requirements.txt

# Copia o conteúdo do seu projeto para o diretório de trabalho no contêiner
COPY . /usr/local/trader/api/

# Expõe a porta em que o Django irá rodar
EXPOSE 8000

# Comando para rodar o servidor Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
