# Generated by Django 3.2.16 on 2024-09-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='value',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='operation',
            name='final_result',
            field=models.CharField(choices=[('profit', 'profit'), ('prejudice', 'prejudice')], default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
