# Generated by Django 3.2.16 on 2024-09-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_operation_final_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(default='teste', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='profit_operation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
