# Generated by Django 3.2.16 on 2024-09-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20240916_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
