# Generated by Django 3.2.16 on 2024-09-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_operation_daily_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(),
        ),
    ]
