# Generated by Django 3.2.16 on 2024-10-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_operation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='profit_operation',
            new_name='profit',
        ),
    ]
